services:
  traefik:
    image: traefik:v3.0
    ports:
      - "80:80"
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./dynamic_conf.yml:/etc/traefik/dynamic_conf.yml:ro # Monte la config
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.file.filename=/etc/traefik/dynamic_conf.yml" # Active le provider fichier
