name: Deploy Traefik
on: [push]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Git Pull et Redémarrage
        run: |
          cd ~/traefik
          git pull origin main
          docker compose up -d
